### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by sskorol** [goxr3plus/Java-Text-To-Speech-Tutorial#1]
@goxr3plus could you please add a license to this repo? Just to make sure it's free to copy and modify your code samples.

Btw, thanks for the tutorial! It was really helpful.

**Comment by goxr3plus** [comment]
Ouuu yeees of course, what license you recommend by the way :)?

Check also google speech recognition tutorials :)

**Comment by sskorol** [comment]
@goxr3plus Apache License 2.0 is quite popular in open source. It can be automatically generated while creating a new project on GitHub. So you can pick it from there.

![image](https://user-images.githubusercontent.com/6638780/39111602-639b6e88-46de-11e8-8309-2e94ca797320.png)

**Comment by goxr3plus** [comment]
You are ready :) Hope you best luck, anything you want, ask, recommend just drop a message and i will help :) :)
